name: le21_dev

services:
  db:
    image: mysql:8
    container_name: le21_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: le_21
      MYSQL_USER: le_21
      MYSQL_PASSWORD: le_21
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -proot --silent"]
      interval: 5s
      timeout: 5s
      retries: 30

  api:
    container_name: le21_api
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      APP_ENV: prod
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: mysql://le_21:le_21@db:3306/le_21?serverVersion=8.4
      DB_HOST: db
      DB_PORT: "3306"
      DB_USER: le_21
      DB_PASSWORD: le_21
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:80"     # http://localhost:8080

  front:
    container_name: le21_front
    build:
      context: .
      dockerfile: Dockerfile.front
      args:
        VITE_API_URL: "http://localhost:8080"
    ports:
      - "3000:80"     # http://localhost:3000
    depends_on:
      - api
