services:
  db:
    image: mysql:8.0
    container_name: le21_db
    environment:
      MYSQL_DATABASE: le_21
      MYSQL_USER: le_21
      MYSQL_PASSWORD: le_21
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-hle21_db", "-uroot", "-proot", "--silent"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - dbdata:/var/lib/mysql

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: le21_api
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      APP_SECRET: dev
      DATABASE_URL: "mysql://le_21:le_21@db:3306/le_21?serverVersion=8.0"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:80"   
    volumes:
      - ./api:/var/www/html   #  monte le code en bash (Entity visible dans le conteneur)


  front:
    container_name: le21_front
    build:
      context: .
      dockerfile: Dockerfile.front 
      args:
        VITE_API_URL: "http://127.0.0.1:8080"
    ports:
      - "3000:80"     
    depends_on:
      - api

volumes:
  dbdata: