nelmio_cors:
  defaults:
    allow_credentials: true
    allow_origin: ['http://127.0.0.1:3000', 'http://127.0.0.1:5173', 'http://localhost:3000', 'http://localhost:5173', 'https://leTwenty-One-tattoo&piercing.fr' ]
    allow_headers: ['Content-Type', 'Authorization']
    allow_methods: ['GET','OPTIONS']
    max_age: 3600
  paths:
    '^/api': ~
    '^/upload': ~