
vich_uploader:
  db_driver: orm
  metadata: { type: attribute }
  mappings:
    media_files:
      uri_prefix: /uploads/media
      upload_destination: '%kernel.project_dir%/public/uploads/media'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    flash_images:
      uri_prefix: /uploads/flashes
      upload_destination: '%kernel.project_dir%/public/uploads/flashes'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    company_logos:
      uri_prefix: /uploads/logos
      upload_destination: '%kernel.project_dir%/public/uploads/logos'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer