
vich_uploader:
  db_driver: orm
  metadata: { type: attribute }
  mappings:
    media_files:
      upload_destination: '%kernel.project_dir%/public/uploads/media'
    flash_images:
      upload_destination: '%kernel.project_dir%/public/uploads/flashes'
    company_logos:
      upload_destination: '%kernel.project_dir%/public/uploads/logos'